from . import res_partner
from . import clinic_surgery_procedure
from . import clinic_surgery_case
from . import clinic_postop_consult
from . import surgery_config_settings
from . import operating_block
from . import sign_request
from . import operating_block_slots
from . import clinic_postop_followup
from . import admission_point
from . import account_move
from . import surgery_case_dashboard
from . import sign_request_item
